name: Syntax check
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yml
  prettier:
    name: Prettier
    uses: ./.github/workflows/prettier.yml
