name: content
on:
  push:
    paths:
      - static/**
      - manager.ts
      - package.json
jobs:
  json-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run compile