name: Publish
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build project
    uses: simonyiszk/schdesign-logotar/.github/workflows/build.yml@main
  deploy:
    needs: build
    name: Deploy project
    uses: simonyiszk/schdesign-logotar/.github/workflows/deploy.yml@main
