name: Publish
on:
  push:
    branches:
      - main
jobs:
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yml
  prettier:
    name: Prettier
    uses: ./.github/workflows/prettier.yml
  build:
    if: github.repository_owner == 'simonyiszk'
    name: Build project
    uses: ./.github/workflows/build.yml
  deploy:
    if: github.repository_owner == 'simonyiszk'
    needs: build
    name: Deploy project
    uses: ./.github/workflows/deploy.yml
